services:
  # default configuration for services in *this* file
  _defaults:
    public: true        # Allows your services to be retrieved from the container.
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  IM\Fabric\Bundle\AndroidServicesBundle\AndroidServicesApi: ~
  IM\Fabric\Bundle\AndroidServicesBundle\Factory\AndroidPublisherService: ~
