name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  workflow_call:
    uses: immediate-media/github-actions-public/.github/workflows/php-package-testing.yml@main
